name: Test SSH Connection

on:
  push:
    paths:
      - 'test_ssh_trigger/*'
  workflow_dispatch:

  
jobs:
  test_ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AIKEN_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa aiken.ce.pdn.ac.lk >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no e19492@aiken.ce.pdn.ac.lk exit 

    - name: Run test script on Aiken server
      run: ssh e19492@aiken.ce.pdn.ac.lk 'cd ~/CO544/project && bash test_script.sh'


      