name: Test SSH Connection

on:
  push:
    paths:
      - 'test_ssh_trigger/*'
  workflow_dispatch:

jobs:
  test_ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.5
      with:
        ssh-private-key: ${{ secrets.AIKEN_SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}

    - name: Run test script on Aiken server
      run: |
        ssh -o StrictHostKeyChecking=no e19492@aiken.ce.pdn.ac.lk 'cd ~/CO544/project && bash test_script.sh'
